### ISSUE TITLE
Part of Nocturnal has not been applied to Settings.

### ISSUE THREAD

**Issue by Official-Darkn** [FlashAL/Nocturnal-discord-theme#2]
User Settings - https://cdn.discordapp.com/attachments/695430418492555314/767069869144801300/Screen_Shot_2020-10-17_at_1.00.44_PM.png
Server Boosts - https://cdn.discordapp.com/attachments/695430418492555314/767070540170264586/Screen_Shot_2020-10-17_at_1.03.10_PM.png
Nitro Settings - https://cdn.discordapp.com/attachments/695430418492555314/767070544134668348/Screen_Shot_2020-10-17_at_1.03.35_PM.png
Payment Method - https://cdn.discordapp.com/attachments/695430418492555314/767071432525742120/Screen_Shot_2020-10-17_at_1.07.47_PM.png
Nitro Button Broken - https://cdn.discordapp.com/attachments/695430418492555314/767071433750347836/Screen_Shot_2020-10-17_at_1.07.51_PM.png
Connected Accounts - https://cdn.discordapp.com/attachments/695430418492555314/767070544159834152/Screen_Shot_2020-10-17_at_1.03.50_PM.png
Buttons - https://cdn.discordapp.com/attachments/695430418492555314/767071079754629130/Screen_Shot_2020-10-17_at_1.06.26_PM.png

These parts of Settings has not been applied with Nocturnal.

**Comment by FlashAL** [comment]
fixed all bugs except Buttons and Server Boosts
Buttons - fixing this bug is not possible until discord developers provide working block diagrams of html code.
Server Boosts - I cannot fix this bug since I do not have discord nitro (the one with boosts).
